/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EventOrganizingCommitteeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DirectorOfficeOrganization;
import Business.Organization.EventOrganizingCommittee;
import Business.Organization.FinanceDeptOrganization;
import Business.Organization.HRDeptOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.EventOrganizingCommittee;
import Business.UserAccount.UserAccount;
import Business.Validation.ValidationMethods;
import Business.WorkQueue.EventOrganizingCommitteeWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jay_c
 */
public class FundingRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundingRequestPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;

    public FundingRequestPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        jLabel8.setText(userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eNameType = new javax.swing.JTextField();
        eCategory = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eBudget = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        sendRequest = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        eNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 30));

        valueLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, 30));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("EVENT TYPE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        eNameType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNameTypeActionPerformed(evt);
            }
        });
        add(eNameType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, 33));
        add(eCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, 40));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("EVENT CATEGORY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 30));

        eCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCapacityActionPerformed(evt);
            }
        });
        add(eCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 40));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("CAPACITY");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        add(eBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 210, 34));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("BUDGET");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 40));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("EVENT  DATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 133, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 210, 30));

        sendRequest.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        sendRequest.setText("SEND REQUEST");
        sendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestActionPerformed(evt);
            }
        });
        add(sendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, 50));

        backBtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        backBtn.setText("<< BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, 50));

        eNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNameTxtActionPerformed(evt);
            }
        });
        add(eNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("EVENT NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, -1, 230));
        jLabel7.getAccessibleContext().setAccessibleName("resultLabel");

        filler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 390, 490));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void eNameTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNameTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNameTypeActionPerformed

    private void eCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCapacityActionPerformed

    private void sendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestActionPerformed
        // TODO add your handling code here:
        if (ValidationMethods.isStringValidWithSpace(eNameTxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide Name", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isStringValidWithSpace(eNameType.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide Type", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isStringValidWithSpace(eCategory.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide Type", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ValidationMethods.isIntegerPositive(eCapacity.getText())==false){
            JOptionPane.showMessageDialog(null, "Please enter a positive number");
        }
       
        EventOrganizingCommitteeWorkRequest evtwreq = new EventOrganizingCommitteeWorkRequest();
        evtwreq.setEventType(eNameType.getText());
        evtwreq.setEventCatagory(eCategory.getText());
        try{
        evtwreq.setCapacity(Integer.parseInt(eCapacity.getText()));
        evtwreq.setBudget(Double.parseDouble(eBudget.getText()));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter numeric value");
            return;
        }
        evtwreq.setEventDate(jDateChooser1.getDate());
        evtwreq.setSender(userAccount);
        evtwreq.setEventName(eNameTxt.getText());
        evtwreq.setStatus("Pending from Director Organization");
        evtwreq.setResult("Waiting");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DirectorOfficeOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(evtwreq);
            userAccount.getWorkQueue().getWorkRequestList().add(evtwreq);
            
            JOptionPane.showMessageDialog(null, "Sent to Director's office for permission and funding");
        }

    }//GEN-LAST:event_sendRequestActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrganizingCommitteeDashPanel evtOCDP = (EventOrganizingCommitteeDashPanel) component;
        evtOCDP.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void eNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField eBudget;
    private javax.swing.JTextField eCapacity;
    private javax.swing.JTextField eCategory;
    private javax.swing.JTextField eNameTxt;
    private javax.swing.JTextField eNameType;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.Box.Filler filler1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton sendRequest;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
