/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceDeptRole;

import Business.EcoSystem;
import Business.Organization.FinanceDeptOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HRDeptWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jinal_s
 */
public class FinanceDeptDashPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinanceDeptDashPanel
     */
    private JPanel userProcessContainer ;
    private UserAccount account;
    private EcoSystem business;
    private FinanceDeptOrganization financeDeptorganization;
    public FinanceDeptDashPanel(JPanel userProcessContainer, UserAccount account, FinanceDeptOrganization financeDeptOrganization, EcoSystem system) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
      this.account= account;
      this.business= business;
      this.financeDeptorganization= financeDeptOrganization;
      populateTable();
      populateApprovedTable();
     
    }
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)waitingRequests.getModel();
        model.setRowCount(0);
        for(WorkRequest request : financeDeptorganization.getWorkQueue().getWorkRequestList()){
            HRDeptWorkRequest req = (HRDeptWorkRequest)request;
            if(req.getResult().equalsIgnoreCase("waiting")){
            
            
            Object[] row = new Object[8];
            row[0] = ((HRDeptWorkRequest) request);
            row[1] = ((HRDeptWorkRequest) request).getEventType();
            row[2] = ((HRDeptWorkRequest) request).getEventCatagory();
            row[3] = ((HRDeptWorkRequest) request).getCapacity();
            row[4] = ((HRDeptWorkRequest) request).getBudget();
            row[5] = ((HRDeptWorkRequest) request).getEventDate();
            row[6] = request.getSender().getEmployee().getName();
            row[7] = request.getStatus();
            model.addRow(row);
            }
        } 
     }
     private void populateApprovedTable() {
        DefaultTableModel model = (DefaultTableModel)waitingRequests1.getModel();
        model.setRowCount(0);
        for(WorkRequest request : financeDeptorganization.getWorkQueue().getWorkRequestList()){
            HRDeptWorkRequest req = (HRDeptWorkRequest)request;
            if(req.getResult().equalsIgnoreCase("approved")){
            
            
            Object[] row = new Object[8];
            row[0] = ((HRDeptWorkRequest) request);
            row[1] = ((HRDeptWorkRequest) request).getEventType();
            row[2] = ((HRDeptWorkRequest) request).getEventCatagory();
            row[3] = ((HRDeptWorkRequest) request).getCapacity();
            row[4] = ((HRDeptWorkRequest) request).getBudget();
            row[5] = ((HRDeptWorkRequest) request).getEventDate();
            row[6] = request.getSender().getEmployee().getName();
            row[7] = request.getStatus();
            model.addRow(row);
            }
        } 
     }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        waitingRequests = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        waitingRequests1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));
        jLabel5 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton2.setText("REJECT ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 150, 40));

        waitingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Type", "Event Category", "Event Capacity", "Budget", "Event Date", "Sender", "status"
            }
        ));
        jScrollPane3.setViewportView(waitingRequests);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1190, 230));

        waitingRequests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Type", "Event Category", "Event Capacity", "Budget", "Event Date", "Sender", "status"
            }
        ));
        jScrollPane4.setViewportView(waitingRequests1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1190, 230));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel1.setText("ENTERPRISE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel4.setText("Approved Requests");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        filler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1210, 300));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel5.setText("Pending Requests");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        filler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1210, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = waitingRequests.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please make a selection");
            return;
        }
        HRDeptWorkRequest request = (HRDeptWorkRequest)waitingRequests.getValueAt(selectedRow, 0);
        request.setResult("Approved");
        request.setStatus("Decision made by finance Department");
        JOptionPane.showMessageDialog(null, "Funding request approved. Sent back to HR Department");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = waitingRequests1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please make a selection");
            return;
        }
        HRDeptWorkRequest request = (HRDeptWorkRequest)waitingRequests1.getValueAt(selectedRow, 0);
        request.setResult("Rejected");
        request.setStatus("Decision made by finance department");
        JOptionPane.showMessageDialog(null, "Funding Request rejected");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable waitingRequests;
    private javax.swing.JTable waitingRequests1;
    // End of variables declaration//GEN-END:variables

   
}
