/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DirectorOfficeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DirectorOfficeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventOrganizingCommitteeWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jay_c
 */
public class DirectorOfficeDashPanel extends javax.swing.JPanel {

    /**
     * Creates new form DirectorOfficeDashPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DirectorOfficeOrganization directorOrganization;
    private Enterprise enterprise;
    public DirectorOfficeDashPanel(JPanel userProcessContainer, UserAccount account, DirectorOfficeOrganization directorOrganization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.directorOrganization = directorOrganization;
        this.enterprise = enterprise;
        jLabel2.setText(enterprise.getName());
        jLabel3.setText("Welcome, "+userAccount.getUsername());
        
        populateTable();
        populateApprovedTable();
    }
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : directorOrganization.getWorkQueue().getWorkRequestList()){
            EventOrganizingCommitteeWorkRequest req = (EventOrganizingCommitteeWorkRequest)request;
            if(req.getResult().equalsIgnoreCase("Waiting")){
                
            
            Object[] row = new Object[8];
            row[0] = ((EventOrganizingCommitteeWorkRequest) request);
            row[1] = ((EventOrganizingCommitteeWorkRequest) request).getEventType();
            row[2] = ((EventOrganizingCommitteeWorkRequest) request).getEventCatagory();
            row[3] = ((EventOrganizingCommitteeWorkRequest) request).getCapacity();
            row[4] = ((EventOrganizingCommitteeWorkRequest) request).getBudget();
            row[5] = ((EventOrganizingCommitteeWorkRequest) request).getEventDate();
            row[6] = request.getSender().getEmployee().getName();
            row[7] = request.getStatus();
            
            model.addRow(row);
            }
        }
    }
    
    
    public void populateApprovedTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable1.getModel();
        
        model.setRowCount(0);
        for(WorkRequest request : directorOrganization.getWorkQueue().getWorkRequestList()){
            EventOrganizingCommitteeWorkRequest req = (EventOrganizingCommitteeWorkRequest)request;
            if(req.getResult().equalsIgnoreCase("approved")){
            
            Object[] row = new Object[9];
            row[0] = ((EventOrganizingCommitteeWorkRequest) request);
            row[1] = ((EventOrganizingCommitteeWorkRequest) request).getEventType();
            row[2] = ((EventOrganizingCommitteeWorkRequest) request).getEventCatagory();
            row[3] = ((EventOrganizingCommitteeWorkRequest) request).getCapacity();
            row[4] = ((EventOrganizingCommitteeWorkRequest) request).getBudget();
            row[5] = ((EventOrganizingCommitteeWorkRequest) request).getEventDate();
            row[6] = request.getSender().getEmployee().getName();
            row[7] = request.getStatus();
            row[8] = req.getAcceptingEnterprise();
            
            model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setForeground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Type", "Catagory", "Capacity", "Event Budget", "Event Date", "Sender", "Status"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(5).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(6).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1180, 185));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 41));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton2.setText("REJECT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, 41));

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Type", "Catagory", "Capacity", "Event Budget", "Event Date", "Sender", "Status", "Accepting Enterprise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);
        if (workRequestJTable1.getColumnModel().getColumnCount() > 0) {
            workRequestJTable1.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(4).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(5).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(6).setResizable(false);
            workRequestJTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 1180, 185));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel1.setText("ENTERPRISE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setText("Approved Requests");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setText("Pending Requests");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        filler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1210, 280));

        filler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1210, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Make a selection.");
            return;
        }
        EventOrganizingCommitteeWorkRequest request = (EventOrganizingCommitteeWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setResult("Approved");
        request.setStatus("Decision made by director organization");
        JOptionPane.showMessageDialog(null, "Request Approved. Sent back to Event Organizing Committee.");

        populateTable();
        populateApprovedTable();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        EventOrganizingCommitteeWorkRequest request = (EventOrganizingCommitteeWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setResult("Rejected");
        request.setStatus("Decision made by director organization");
        JOptionPane.showMessageDialog(null, "Request Rejected. Sent back to Event Organizing Committee.");

        populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable workRequestJTable;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
