/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BudgetingDeptRole;

import Business.EcoSystem;
import Business.Event.Event;
import Business.UserAccount.UserAccount;
import Business.Validation.ValidationMethods;
import Business.WorkQueue.EventOrganizingCommitteeWorkRequest;
import Business.WorkQueue.HRDeptWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jay_c
 */
public class UpdateEventInformation extends javax.swing.JPanel {

    /**
     * Creates new form UpdateEventInformation
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem business;
    private WorkRequest request;
            
    public UpdateEventInformation(JPanel userProcessContainer, UserAccount userAccount, EcoSystem business, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        if(request instanceof EventOrganizingCommitteeWorkRequest){
            this.request = (EventOrganizingCommitteeWorkRequest) request;
            eName.setText(((EventOrganizingCommitteeWorkRequest) request).getEventName());
            eType.setText(((EventOrganizingCommitteeWorkRequest) request).getEventType());
            eCatagory.setText(((EventOrganizingCommitteeWorkRequest) request).getEventCatagory());
            eCapacity.setText(String.valueOf(((EventOrganizingCommitteeWorkRequest) request).getCapacity()));
            eDate.setDate(((EventOrganizingCommitteeWorkRequest) request).getEventDate());
            
        }
        else{
            this.request = (HRDeptWorkRequest) request;
            eName.setText(((HRDeptWorkRequest) request).getEventName());
            eType.setText(((HRDeptWorkRequest) request).getEventType());
            eCatagory.setText(((HRDeptWorkRequest) request).getEventCatagory());
            eCapacity.setText(String.valueOf(((HRDeptWorkRequest) request).getCapacity()));
            eDate.setDate(((HRDeptWorkRequest) request).getEventDate());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ePrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        eCatagory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eVenue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eTime = new javax.swing.JTextField();
        updateEventButton = new javax.swing.JButton();
        eName = new javax.swing.JTextField();
        eType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePriceActionPerformed(evt);
            }
        });
        add(ePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 186, 35));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("PRICE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 45));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("EVENT DATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, 34));
        add(eDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 186, 34));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("EVENT TYPE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        add(eCatagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 184, 37));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("EVENT NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("EVENT CATEGORY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        eCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCapacityActionPerformed(evt);
            }
        });
        add(eCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 186, 38));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("CAPACITY");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, 35));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("EVENT VENUE");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, 36));
        add(eVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 186, 36));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("EVENT TIME");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, 39));

        eTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTimeActionPerformed(evt);
            }
        });
        add(eTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 186, 39));

        updateEventButton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        updateEventButton.setText("UPDATE AND ADD TO PORTAL");
        updateEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEventButtonActionPerformed(evt);
            }
        });
        add(updateEventButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, 55));
        add(eName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 190, 30));

        eType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTypeActionPerformed(evt);
            }
        });
        add(eType, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 192, 180, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setText("EVENT INFORMATION");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEventButtonActionPerformed
        // TODO add your handling code here:
  if(ValidationMethods.isStringValidWithSpace(eName.getText())== false){
            JOptionPane.showMessageDialog(null, "Please provide Name", "Info", JOptionPane.ERROR_MESSAGE);
return;        
}
        if(ValidationMethods.isStringValidWithSpace(eType.getText())== false){
            JOptionPane.showMessageDialog(null, "Please provide Type", "Info", JOptionPane.ERROR_MESSAGE);
return;        
}
        if(ValidationMethods.isIntegerPositive(eCapacity.getText())== false){
            JOptionPane.showMessageDialog(null, "Please provide valid input", "Info", JOptionPane.ERROR_MESSAGE);
      return;  
      }
        if(ValidationMethods.isIntegerPositive(ePrice.getText())== false){
            JOptionPane.showMessageDialog(null, "Please provide valid input", "Info", JOptionPane.ERROR_MESSAGE);
      return; 
        }
        String eventName = eName.getText();
        String eventType = eType.getText();
        String eventCatagory = eCatagory.getText();
        int eventCapacity = Integer.parseInt(eCapacity.getText());
        Date eventDate = eDate.getDate();

        Double price = Double.parseDouble(ePrice.getText());
        String venue = eVenue.getText();
        String time = eTime.getText();
        business.getEventDirectory().createEvent(eventName, eventType, eventCatagory, eventCapacity, price, eventDate, venue, time);
        request.setStatus("Event Published");
        JOptionPane.showMessageDialog(null, "Updated!", "Info", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_updateEventButtonActionPerformed

    private void eTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTimeActionPerformed

    private void eCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCapacityActionPerformed

    private void ePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePriceActionPerformed

    private void eTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eCapacity;
    private javax.swing.JTextField eCatagory;
    private com.toedter.calendar.JDateChooser eDate;
    private javax.swing.JTextField eName;
    private javax.swing.JTextField ePrice;
    private javax.swing.JTextField eTime;
    private javax.swing.JTextField eType;
    private javax.swing.JTextField eVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton updateEventButton;
    // End of variables declaration//GEN-END:variables
}
