/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRDeptRole;

/**
 *
 * @author sapar
 */
import Business.Enterprise.Enterprise;
import Business.Organization.DirectorOfficeOrganization;
import Business.Organization.FinanceDeptOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Validation.ValidationMethods;
import Business.WorkQueue.HRDeptWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class HRFundingRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form HRFundingRequestPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    HRFundingRequestPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        valueLabel.setText(enterprise.getName());
        user.setText(userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capacity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        valueLabel = new javax.swing.JLabel();
        sendRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        eventName = new javax.swing.JTextField();
        eventBudget = new javax.swing.JTextField();
        eventType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventCatagory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220), new java.awt.Dimension(220, 220));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capacity.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 223, 30));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("BUDGET");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 20));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("EVENT DATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 24));

        user.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 30));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 233, 38));

        valueLabel.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, -1));

        sendRequest.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sendRequest.setText("SEND REQUEST ");
        sendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestActionPerformed(evt);
            }
        });
        add(sendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, 43));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("EVENT TYPE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        backBtn.setBackground(new java.awt.Color(204, 255, 204));
        backBtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 96, 40));

        eventName.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        eventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameActionPerformed(evt);
            }
        });
        add(eventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 223, 30));

        eventBudget.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        eventBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBudgetActionPerformed(evt);
            }
        });
        add(eventBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 223, 30));

        eventType.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(eventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 223, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("EVENT NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("EVENT CATEGORY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        eventCatagory.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        eventCatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventCatagoryActionPerformed(evt);
            }
        });
        add(eventCatagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 223, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("CAPACITY");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 20));

        enterpriseLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        enterpriseLabel1.setText("ENTERPRISE");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 30));

        filler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 410, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestActionPerformed
        // TODO add your handling code here:
        if (ValidationMethods.isStringValidWithSpace(eventName.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide Name", "Info", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        if (ValidationMethods.isStringValidWithSpace(eventType.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide Type", "Info", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        if (ValidationMethods.isIntegerPositive(capacity.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide valid input", "Info", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        if (ValidationMethods.isIntegerPositive(eventBudget.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please provide valid input", "Info", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        HRDeptWorkRequest evtwreq = new HRDeptWorkRequest();
        evtwreq.setEventType(eventType.getText());
        evtwreq.setEventCatagory(eventCatagory.getText());
        evtwreq.setCapacity(Integer.parseInt(capacity.getText()));
        evtwreq.setBudget(Double.parseDouble(eventBudget.getText()));
        evtwreq.setEventDate(jDateChooser1.getDate());
        evtwreq.setSender(userAccount);
        evtwreq.setEventName(eventBudget.getText());
        evtwreq.setStatus("Pending from Finance Department");
        evtwreq.setResult("Waiting");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof FinanceDeptOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(evtwreq);
            userAccount.getWorkQueue().getWorkRequestList().add(evtwreq);
            JOptionPane.showMessageDialog(null, "Sent to Finance Department for funding request");
        }

    }//GEN-LAST:event_sendRequestActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HRDeptDashPanel evtOCDP = (HRDeptDashPanel) component;
        evtOCDP.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void eventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameActionPerformed

    private void eventBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventBudgetActionPerformed

    private void eventCatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventCatagoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eventCatagoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField capacity;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JTextField eventBudget;
    private javax.swing.JTextField eventCatagory;
    private javax.swing.JTextField eventName;
    private javax.swing.JTextField eventType;
    private javax.swing.Box.Filler filler1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton sendRequest;
    private javax.swing.JLabel user;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
