/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegistrationPanel;

import Business.Captcha.Captcha;
import Business.Customers.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Email.EmailAuth;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Role.CustomerRole;
import Business.Validation.ValidationMethods;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jay_c
 */
public class RegistrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    private CustomerRole role;
    String sender = "jaychitalia2@gmail.com";

    public RegistrationPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil dB4OUtil, CustomerRole role) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.role = role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel1.setText("REGISTRATION PANEL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("LAST NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("EMAIL");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("CONTACT");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));
        add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 200, 30));
        add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 200, 30));
        add(lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 30));
        add(contacttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("USERNAME");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 30));
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("REGISTER");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 230, 50));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 270, 80));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton2.setText("GENERATE CAPTCHA");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 190, 40));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 270, 80));

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton3.setText("VERIFY");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 110, 40));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 350, 70));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 200, 30));

        jCheckBox1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCheckBox1.setText("SHOW PASSWORD");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("CONFIRM PASSWORD");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("FIRST NAME");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        if (ValidationMethods.isStringValidWithSpace(fnametxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter valid input", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isStringValidWithSpace(lnametxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter valid input", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isEmailValid(emailtxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter valid Email-id", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isStringValidContact(contacttxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter valid Phone Number", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ValidationMethods.isStringValidWithSpace(usernametxt.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Please enter username", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String passwordreal = jPasswordField1.getText();
        String passwordconfirm = jPasswordField2.getText();
        if (ValidationMethods.isPasswordAndConfirmPasswordSame(passwordreal, passwordconfirm)==false) {
            JOptionPane.showMessageDialog(null, "", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String username = usernametxt.getText();
        for(Customer cust: system.getCustomerList().getCustomerList()){
            if(system.checkIfUserIsUnique(username)){
                if(system.checkIfUserIsUnique(username)==false){
                    JOptionPane.showMessageDialog(null, "Username is already taken by a customer");
                    return;
                }
            }
        }
        for(Network net: system.getNetworkList()){
            if(system.checkIfUserIsUnique(username)==false){
                JOptionPane.showMessageDialog(null, "Username is already assigned.");
                return;
            }
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getUserDirectory().checkIfUsernameIsUnique(username)==false){
                    JOptionPane.showMessageDialog(null, "Username is already assigned.");
                    return;
                }
                for(Organization org: ent.getOrganizationDirectory().getOrganizationList()){
                    if(org.getUserDirectory().checkIfUsernameIsUnique(username)==false){
                        JOptionPane.showMessageDialog(null, "Username is already assigned.");
                        return;
                    }
                }
            }
        }
        
        
        String fname = fnametxt.getText();
        String lname = lnametxt.getText();
        String email = emailtxt.getText();
        String contact = contacttxt.getText();
        String message = "Congratulations! You have been successfully registered."+fname+" "+lname+"!";
        system.getCustomerList().createCustomer(fname, lname, email, contact);
        system.getUserDirectory().createCustomerAccount(username, passwordreal, role);
        JOptionPane.showMessageDialog(null, "You have been successfully registered. You can login now.");
        
        
        
        dB4OUtil.storeSystem(system);
        try {
            EmailAuth.postMail(email, message, sender);
        } catch (MessagingException ex) {
            Logger.getLogger(RegistrationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(Captcha.generateCaptcha());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (fnametxt.getText().equalsIgnoreCase(jLabel3.getText())) {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        // TODO add your handling code here:
        String c = "" + evt.getKeyChar();
        String checker = jPasswordField2.getText();
        if (!c.isEmpty()) {
            checker += c;
        }
        if (jPasswordField1.getText().equals(checker)) {
            jPasswordField2.setBackground(Color.green);
            jButton1.setEnabled(true);
        } else {
            jPasswordField2.setBackground(Color.red);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contacttxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
